const vistorias = [
    {
        data: '2024-07-01',
        modelo: 'Escavadeira CAT 320D',
        aprovado: true,
        responsavel: 'João Silva',
        local: 'Obra A',
        itensInternos: {
            freioDePe: 'Ok',
            freioDeEstacionamento: 'Ok',
            motorDePartida: 'Ok',
            limpadorDeParaBrisa: 'Ok',
            lavadorDeParaBrisa: 'Ok',
            buzina: 'Ok',
            farois: 'Ok',
            setasDianteiras: 'Ok',
            setasTraseiras: 'Ok',
            luzDeFreio: 'Ok',
            luzDeRe: 'Ok',
            trianguloDeAdvertencia: 'Ok',
            extintorDeSeguranca: 'Ok',
            espelhosRetrovisores: 'Ok',
            indicadoresDePainel: 'Ok',
            cintoDeSeguranca: 'Ok',
            macaco: 'Ok',
            chaveDeRoda: 'Ok',
            nivelDeOleo: 'Ok',
            nivelDeAgua: 'Ok',
            ruidoInterno: 'Ok',
        },
        itensExternos: {
            condicoesDosPneus: 'Ok',
            pneuEstoque: 'Ok',
            vidros: 'Ok',
            portas: 'Ok',
            lataria: 'Ok',
        },
        observacoes: 'Nenhuma observação.'
    },
    {
        data: '2024-07-15',
        modelo: 'Pá Carregadeira Komatsu WA320',
        aprovado: false,
        responsavel: 'Maria Oliveira',
        local: 'Obra B',
        itensInternos: {
            freioDePe: 'Não Ok',
            freioDeEstacionamento: 'Ok',
            motorDePartida: 'Ok',
            limpadorDeParaBrisa: 'Ok',
            lavadorDeParaBrisa: 'Ok',
            buzina: 'Ok',
            farois: 'Ok',
            setasDianteiras: 'Ok',
            setasTraseiras: 'Ok',
            luzDeFreio: 'Ok',
            luzDeRe: 'Ok',
            trianguloDeAdvertencia: 'Ok',
            extintorDeSeguranca: 'Ok',
            espelhosRetrovisores: 'Ok',
            indicadoresDePainel: 'Ok',
            cintoDeSeguranca: 'Ok',
            macaco: 'Ok',
            chaveDeRoda: 'Ok',
            nivelDeOleo: 'Ok',
            nivelDeAgua: 'Ok',
            ruidoInterno: 'Ok',
        },
        itensExternos: {
            condicoesDosPneus: 'Ok',
            pneuEstoque: 'Ok',
            vidros: 'Ok',
            portas: 'Ok',
            lataria: 'Não Ok',
        },
        observacoes: 'Freio de pé com problema. Lataria com danos.'
    },
    {
        data: '2024-07-20',
        modelo: 'Retroescavadeira JCB 3CX',
        aprovado: true,
        responsavel: 'Carlos Pereira',
        local: 'Obra C',
        itensInternos: {
            freioDePe: 'Ok',
            freioDeEstacionamento: 'Ok',
            motorDePartida: 'Ok',
            limpadorDeParaBrisa: 'Ok',
            lavadorDeParaBrisa: 'Ok',
            buzina: 'Ok',
            farois: 'Ok',
            setasDianteiras: 'Ok',
            setasTraseiras: 'Ok',
            luzDeFreio: 'Ok',
            luzDeRe: 'Ok',
            trianguloDeAdvertencia: 'Ok',
            extintorDeSeguranca: 'Ok',
            espelhosRetrovisores: 'Ok',
            indicadoresDePainel: 'Ok',
            cintoDeSeguranca: 'Ok',
            macaco: 'Ok',
            chaveDeRoda: 'Ok',
            nivelDeOleo: 'Ok',
            nivelDeAgua: 'Ok',
            ruidoInterno: 'Ok',
        },
        itensExternos: {
            condicoesDosPneus: 'Ok',
            pneuEstoque: 'Ok',
            vidros: 'Ok',
            portas: 'Ok',
            lataria: 'Ok',
        },
        observacoes: 'Nenhuma observação.'
    }
];

export { vistorias };
